CREATE TABLE `inbody_records` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`student_id` integer NOT NULL,
	`measured_at` text NOT NULL,
	`weight_kg` real,
	`body_fat_pct` real,
	`skeletal_muscle_kg` real,
	`body_fat_kg` real,
	`visceral_fat_level` real,
	`body_age` real,
	`bmi` real,
	`bmr_kcal` real,
	`total_water_l` real,
	`protein_kg` real,
	`muscle_left_arm` real,
	`muscle_right_arm` real,
	`muscle_trunk` real,
	`muscle_left_leg` real,
	`muscle_right_leg` real,
	`fat_left_arm` real,
	`fat_right_arm` real,
	`fat_trunk` real,
	`fat_left_leg` real,
	`fat_right_leg` real,
	`coach_notes` text,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	`updated_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	FOREIGN KEY (`student_id`) REFERENCES `students`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `students` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`coach_id` integer DEFAULT 1 NOT NULL,
	`name` text NOT NULL,
	`gender` text NOT NULL,
	`birthday` text,
	`phone` text,
	`email` text,
	`goal` text NOT NULL,
	`custom_goal` text,
	`weekly_class_count` integer NOT NULL,
	`weekly_gym_count` integer NOT NULL,
	`notes` text,
	`deleted_at` text,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	`updated_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);
